### ISSUE TITLE
Test suite failing to parse LaTeX error

### ISSUE THREAD

**Issue by byorgey** [cchalmers/texrunner#10]
The test suite is failing with some messages like this:
```
expected: UndefinedControlSequence "\\hobx"
 but got: UnknownError "Undefined control sequence."
```
e.g. see https://travis-ci.org/cchalmers/texrunner/jobs/612206058 .  It seems like the expected error message is in an unexpected format, or something like that.

**Comment by cchalmers** [comment]
Ah, I didn't realise you'd written all these tests. Yeah, parsing tex's output is difficult because of stuff like this, it's just not consistent between versions and distributions. I'm not really sure the best thing to do about this.

Hopefully it's not too bad to modify [the parser](https://github.com/cchalmers/texrunner/blob/master/src/System/Texrunner/Parse.hs#L221-L236)  to handle different variants. Would be good if we could get the logs that it failed to parse.

**Comment by byorgey** [comment]
I didn't write the tests, [you did](https://github.com/cchalmers/texrunner/blob/master/src/System/Texrunner/Parse.hs#L6-L9)!  =)   Makes sense though, I'll look into updating the parser.  I know it fails on my local machine too so it shouldn't be too hard to get our hands on the failing logs.

**Comment by byorgey** [comment]
So that one was pretty easy to fix actually.  But there's still one other that's failing and I have no idea why.  As far as I can tell, TeX is returning the correct error message, but it is getting parsed as something different.

**Comment by cchalmers** [comment]
Ah, so I did. Git's useless [history](https://github.com/cchalmers/texrunner/commits/master/tests/Tex/LogParse.hs) confused me (yours was the only picture in the contributors of the file). Can you post the other error that's getting parsed incorrectly?

**Comment by byorgey** [comment]
It's the test for "illegal unit" which is parsing an "emergency stop" instead.  But when I tried it on my machine the logs I could see had an "illegal unit" error first and then an "emergency stop" error after that.  But I'm not really sure whether what I'm seeing is exactly the same thing that the test is seeing.
